source 'https://rubygems.org'

gem 'unicorn', require: false
gem 'god', require: false

gem 'sinatra'
gem 'sinatra-contrib'
gem 'erubis'

gem 'redis'
gem 'redis-rack'
gem 'json-jwt'
gem 'activemodel', require: 'active_model'

gem 'rack-flash3'
gem 'mail'

gem 'rdiscount'
gem 'rack-utf8_sanitizer'

group :test do
  gem 'rspec'
  gem 'webrat'
  gem 'fakeredis'
  gem 'rubocop'
  gem 'simplecov'
  gem 'factory_girl'
  gem 'faker'
  gem 'timecop'
  gem 'shoulda-matchers'
  gem 'rake', require: false
  gem 'codeclimate-test-reporter', require: false

  gem 'guard', require: false
  gem 'guard-rspec', require: false
  gem 'guard-rubocop', require: false
  gem 'guard-bundler', require: false
end

group :cli do
  gem 'thor', require: false
end
