# frozen_string_literal: true

source 'https://rubygems.org'

gem 'god', require: false
gem 'unicorn', require: false

gem 'erubis'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activemodel', '~> 4.2', require: 'active_model'
gem 'json-jwt'
gem 'redis'
gem 'redis-rack'

gem 'mail'
gem 'rack-flash3'

gem 'rack-utf8_sanitizer'
gem 'rdiscount'

group :test do
  gem 'shoulda-matchers', require: false
end

group :test, :development do
  gem 'aaf-gumboot'

  gem 'capybara'
  gem 'factory_girl'
  gem 'faker'
  gem 'fakeredis'
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov'
  gem 'timecop'

  gem 'codeclimate-test-reporter', require: false
  gem 'rake', require: false

  gem 'guard', require: false
  gem 'guard-bundler', require: false
  gem 'guard-rspec', require: false
  gem 'guard-rubocop', require: false
end

group :cli do
  gem 'thor', require: false
end
