# frozen_string_literal: true

require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RSpec::Core::RakeTask.new(:spec)
RuboCop::RakeTask.new

task :mkdirs do
  Dir.mkdir_p('logs')
  Dir.mkdir_p('tmp')
end

task default: %i[mkdirs spec rubocop]
