require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RSpec::Core::RakeTask.new(:spec)
RuboCop::RakeTask.new

task :mkdirs do
  Dir.mkdir('logs') unless Dir.exist?('logs')
  Dir.mkdir('tmp') unless Dir.exist?('tmp')
end

task default: [:mkdirs, :spec, :rubocop]
