#! /bin/bash

### BEGIN INIT INFO
# Provides: unicorn
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Starts unicorn for rapidconnect
# Description: Starts unicorn for rapidconnect
### END INIT INFO

USER=rapid
PATH=/home/$USER/.rbenv/bin:/home/$USER/.rbenv/shims:$PATH
DAEMON=unicorn
DAEMON_OPTS="-c /opt/rapidconnect/application/config/unicorn.rb -E production -D"
NAME=unicorn
DESC="Unicorn app for $USER"
PID=/opt/rapidconnect/application/tmp/unicorn.pid

case "$1" in
  start)
        CD_TO_APP_DIR="cd /opt/rapidconnect/application"
        START_DAEMON_PROCESS="bundle exec $DAEMON $DAEMON_OPTS"

        echo -n "Starting $DESC: "
        if [ `whoami` = root ]; then
          su - $USER -c "mkdir -p /opt/rapidconnect/application/tmp" > /dev/null 2>&1
          su - $USER -c "$CD_TO_APP_DIR > /dev/null 2>&1 && $START_DAEMON_PROCESS"
        else
          mkdir -p /opt/rapidconnect/application/tmp > /dev/null 2>&1
          $CD_TO_APP_DIR > /dev/null 2>&1 && $START_DAEMON_PROCESS
        fi
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        kill -QUIT `cat $PID`
        echo "$NAME."
        ;;
  restart)
        echo -n "Restarting $DESC: "
        kill -USR2 `cat $PID`
        echo "$NAME."
        ;;
  reload)
        echo -n "Reloading $DESC configuration: "
        kill -HUP `cat $PID`
        echo "$NAME."
        ;;
  *)
        echo "Usage: $NAME {start|stop|restart|reload}" >&2
        exit 1
        ;;
esac

exit 0
