# frozen_string_literal: true

# Represents the 'https://aaf.edu.au/attributes' claim generated by Rapid
# Connect for research services.
class AttributesClaim
  attr_reader :attributes

  def initialize(iss, aud, subject)
    @attributes = {
      cn: subject[:cn], displayname: subject[:display_name],
      surname: subject[:surname], givenname: subject[:given_name],
      mail: subject[:mail], o: subject[:organization],
      auedupersonsharedtoken: subject[:shared_token],
      edupersonscopedaffiliation: subject[:scoped_affiliation],
      edupersonprincipalname: subject[:principal_name],
      edupersontargetedid: retarget_id(iss, aud, subject)
    }
  end

  private

  def retarget_id(iss, aud, subject)
    principal, mail = subject.values_at(:principal, :mail)

    stored_id(principal, aud) do
      _, _, opaque = principal.split('!')

      # The inclusion of 'mail' here is for backward compatibility. Since we're
      # storing the ID anyway, the retargeted ID won't change if the subject
      # has a new email address.
      new_opaque = hash("#{opaque} #{mail} #{aud}")
      "#{iss}!#{aud}!#{new_opaque}"
    end
  end

  def stored_id(principal, aud)
    anonymized_principal = OpenSSL::Digest::SHA256.hexdigest(principal)
    key = "eptid:#{aud}:#{anonymized_principal}"
    redis = Redis.new

    redis.get(key).tap { |r| return r if r }
    yield.tap { |r| redis.set(key, r) }
  end

  def hash(value)
    OpenSSL::Digest::SHA1.base64digest(value)
  end
end
